spring:
  server:
    use-forward-headers: true
  datasource:
    password:  -- your db password --
    url: jdbc:mysql://localhost:3306/demo
    username: -- your db username --
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  mail:
    host: smtp.gmail.com
    password: -- your password --
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
          timeout: 5000
          writetimeout: 5000
    username: -- your username --
  thymeleaf:
    cache: 'false  '
    suffix: .html

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: -- your google client --
            clientSecret: -- your google clientSecret --
            scope:
              - email
              - profile
          facebook:
            clientId: -- your facebook clientId --
            clientSecret: -- your facebook clientSecret --
            accessTokenUri: https://graph.facebook.com/oauth/access_token
            userAuthorizationUri: https://www.facebook.com/dialog/oauth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
            resource:
              userInfoUri: https://graph.facebook.com/me
            scope:
              - email
              - public_profile
          github:
            clientId:  -- your github clientId --
            clientSecret: -- your github clientSecret --
            scope:
              - user:email
              - read:user